import { faCircleArrowLeft } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useQuery } from "react-query";
import UsersApi from "../../api/users";
import Card from "../../components/Card";
import HeaderCard from "../../components/HeaderCard";
import Page from "../../components/Page";
import Sidebar from "../../components/Sidebar";
import styles from "../../styles/Home.module.css";

const SpecificUser: NextPage = () => {
  const router = useRouter();
  const { userid } = router.query;
  console.log(userid);

  const user = useQuery("user", () => UsersApi.getOne(userid as string), {
    enabled: !!userid,
  }); // this cast needs fixing!

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex-row w-full'>
        <Sidebar />
        <Page>
          <HeaderCard
            header='Users'
            navOption={
              <Link href='/users'>
                <div>
                  <FontAwesomeIcon className=' w-6 text-orange-600 hover:text-orange-800' icon={faCircleArrowLeft} />
                </div>
              </Link>
            }
            actionButton={<div></div>}
          />
          <Card
            className='w-64'
            header={user.data ? user.data.first_name + " " + user.data.last_name : ""}
            text={user.data ? user.data.email + " " + user.data.role : ""}
          />
        </Page>
      </div>
    </div>
  );
};

export default SpecificUser;
